### PR TITLE
add position to planet translation

### PR DESCRIPTION
**Pull request by 11qats**
Handles rotated system tiles, different tile scales, and destroyed planets. Doesn't handle mirage yet, and the translation of the potato shaped planets in the Clan of Saar home system is not great.

Currently it grabs the system tile scale from Hex.SCALE, which is 1.5, but the scale of the tiles in the test setup was still 1.667 so it doesn't work great on the test setup without also changing Hex.SCALE

The tolerance for determining if a position is on a planet can be changed by increasing/decreasing RADIUS_BUFFER.

### CODE REVIEW

**Comment by 11qats** [comment]
haha sometimes I can be pretty foolish. That is definitely a better solution and would have saved me a lot of time. I'll make those changes tonight.

**Comment by darrellanderson** [comment]
It would also be good if you could get the planet count / is home by looking at the System instead of hard-coding.  That way when homebrew folks add new tiles they just need to register them with System and other things just work.

Some planets in System have offsets for when they are aren't at the standard location.

**Comment by 11qats** [comment]
Sounds good I can make those changes as well. Are the current offsets for non-standard planets in system-data.js used/going to be used for anything else or can I change them if they don't line up nicely with the planets? 

Any thoughts on how I'm handling destroyed planets?

**Comment by darrellanderson** [comment]
I suspect anything that destroys a planet will mark the System.js Planet object -- you could look for that instead of asking the caller to tell you (the "destroyed" Planet flag isn't there yet, feel free to add it).

The positions in system.data.js are straight copied over from TTS so they're probably only off by a scalar, but by all means please fix! 😄  Right now nothing else is using them, the important consumer for your method will be `src/lib/unit/unit-plastic.js` the `UnitPlastic.assignPlanets` method.  (It will probably want both "what planet is closest to this plastic" as well as "is this plastic *directly* on the planet for a small number of cases like mech that can be in space if not placed on a planet.)

**Review by darrellanderson — APPROVED** [review]
Looks good!

**Pull request merged**
